name: mi_app
description: App de telemetría SOMI

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔵 BLE
  flutter_blue_plus: ^1.32.8

  # 🌐 HTTP (envío a VPS / Telegram)
  http: ^1.2.1

  # 💾 almacenamiento local (reportes pendientes)
  shared_preferences: ^2.2.2

  # 🧾 iconos
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"